
spring:
  application:
    name: travel
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?useSSL=true&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  redis:
    host: ${TRAVEL_REDIS_HOST}
    port: ${TRAVEL_REDIS_PORT}
    password: ${TRAVEL_REDIS_PASSWORD}
    database: ${TRAVEL_REDIS_DATABASE}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  jpa:
    show-sql: ${SHOW_SQL}
token:
  secret: ${SECRET_TOKEN}
  algorithm: HS256
  expiresSecond: 604800
server:
  port: 8080